### ISSUE TITLE
complie Failure

### ISSUE THREAD

**Issue by cbogithub** [dsmorozov/qputty-qt5#1]
:\QTlib\qputty-qt5>qmake
'git' is not recognized as an internal or external command,
operable program or batch file.
'git' is not recognized as an internal or external command,
operable program or batch file.
Project MESSAGE: MODE: Release
Project MESSAGE: qPutty with PUTTY_HOME=./putty GEN_SBCSDAT=yes KERBEROS=yes GSSGLUE=yes
'git' is not recognized as an internal or external command,
operable program or batch file.
'git' is not recognized as an internal or external command,
operable program or batch file.
Project MESSAGE: MODE: Release
Project MESSAGE: qPutty with PUTTY_HOME=./putty GEN_SBCSDAT=yes KERBEROS=yes GSSGLUE=yes
WARNING: Failure to find: putty\be_all_s.c
WARNING: Failure to find: putty\callback.c
WARNING: Failure to find: putty\cmdline.c
WARNING: Failure to find: putty\conf.c
WARNING: Failure to find: putty\config.c
WARNING: Failure to find: putty\cproxy.c
WARNING: Failure to find: putty\dialog.c
WARNING: Failure to find: putty\ldisc.c
WARNING: Failure to find: putty\ldiscucs.c
WARNING: Failure to find: putty\logging.c
WARNING: Failure to find: putty\minibidi.c
WARNING: Failure to find: putty\misc.c
WARNING: Failure to find: putty\pinger.c
WARNING: Failure to find: putty\portfwd.c
WARNING: Failure to find: putty\proxy.c
WARNING: Failure to find: putty\raw.c
WARNING: Failure to find: putty\rlogin.c
WARNING: Failure to find: putty\sercfg.c
WARNING: Failure to find: putty\settings.c
WARNING: Failure to find: putty\ssh.c
WARNING: Failure to find: putty\sshaes.c
WARNING: Failure to find: putty\ssharcf.c
WARNING: Failure to find: putty\sshblowf.c
WARNING: Failure to find: putty\sshbn.c
WARNING: Failure to find: putty\sshcrc.c
WARNING: Failure to find: putty\sshcrcda.c
WARNING: Failure to find: putty\sshdes.c
WARNING: Failure to find: putty\sshdh.c
WARNING: Failure to find: putty\sshdss.c
WARNING: Failure to find: putty\sshmd5.c
WARNING: Failure to find: putty\sshpubk.c
WARNING: Failure to find: putty\sshrand.c
WARNING: Failure to find: putty\sshrsa.c
WARNING: Failure to find: putty\sshsh256.c
WARNING: Failure to find: putty\sshsh512.c
WARNING: Failure to find: putty\sshsha.c
WARNING: Failure to find: putty\sshshare.c
WARNING: Failure to find: putty\sshzlib.c
WARNING: Failure to find: putty\telnet.c
WARNING: Failure to find: putty\terminal.c
WARNING: Failure to find: putty\timing.c
WARNING: Failure to find: putty\tree234.c
WARNING: Failure to find: putty\version.c
WARNING: Failure to find: putty\wcwidth.c
WARNING: Failure to find: putty\wildcard.c
WARNING: Failure to find: putty\x11fwd.c
WARNING: Failure to find: putty\import.c
WARNING: Failure to find: putty\charset\fromucs.c
WARNING: Failure to find: putty\charset\macenc.c
WARNING: Failure to find: putty\charset\localenc.c
WARNING: Failure to find: putty\charset\mimeenc.c
WARNING: Failure to find: putty\charset\sbcs.c
WARNING: Failure to find: putty\charset\toucs.c
WARNING: Failure to find: putty\charset\slookup.c
WARNING: Failure to find: putty\charset\utf8.c
WARNING: Failure to find: putty\charset\xenc.c
WARNING: Failure to find: putty\windows\winmisc.c
WARNING: Failure to find: putty\windows\windefs.c
WARNING: Failure to find: putty\windows\wintime.c
WARNING: Failure to find: putty\windows\wincfg.c
WARNING: Failure to find: putty\windows\winnet.c
WARNING: Failure to find: putty\windows\winnoise.c
WARNING: Failure to find: putty\windows\winprint.c
WARNING: Failure to find: putty\windows\winproxy.c
WARNING: Failure to find: putty\windows\winser.c
WARNING: Failure to find: putty\windows\winstore.c
WARNING: Failure to find: putty\windows\winucs.c
WARNING: Failure to find: putty\windows\winhandl.c
WARNING: Failure to find: putty\windows\winhelp.c
WARNING: Failure to find: putty\windows\winpgntc.c
WARNING: Failure to find: putty\windows\winshare.c
WARNING: Failure to find: putty\windows\winutils.c
WARNING: Failure to find: putty\windows\winx11.c
WARNING: Failure to find: putty\windows\winjump.c
WARNING: Failure to find: putty\windows\wingss.c
WARNING: Failure to find: putty\sshgssc.c
WARNING: Failure to find: putty\pgssapi.c
'git' is not recognized as an internal or external command,
operable program or batch file.
'git' is not recognized as an internal or external command,
operable program or batch file.
Project MESSAGE: MODE: Debug
Project MESSAGE: qPutty with PUTTY_HOME=./putty GEN_SBCSDAT=yes KERBEROS=yes GSSGLUE=yes
WARNING: Failure to find: putty\be_all_s.c
WARNING: Failure to find: putty\callback.c
WARNING: Failure to find: putty\cmdline.c
WARNING: Failure to find: putty\conf.c
WARNING: Failure to find: putty\config.c
WARNING: Failure to find: putty\cproxy.c
WARNING: Failure to find: putty\dialog.c
WARNING: Failure to find: putty\ldisc.c
WARNING: Failure to find: putty\ldiscucs.c
WARNING: Failure to find: putty\logging.c
WARNING: Failure to find: putty\minibidi.c
WARNING: Failure to find: putty\misc.c
WARNING: Failure to find: putty\pinger.c
WARNING: Failure to find: putty\portfwd.c
WARNING: Failure to find: putty\proxy.c
WARNING: Failure to find: putty\raw.c
WARNING: Failure to find: putty\rlogin.c
WARNING: Failure to find: putty\sercfg.c
WARNING: Failure to find: putty\settings.c
WARNING: Failure to find: putty\ssh.c
WARNING: Failure to find: putty\sshaes.c
WARNING: Failure to find: putty\ssharcf.c
WARNING: Failure to find: putty\sshblowf.c
WARNING: Failure to find: putty\sshbn.c
WARNING: Failure to find: putty\sshcrc.c
WARNING: Failure to find: putty\sshcrcda.c
WARNING: Failure to find: putty\sshdes.c
WARNING: Failure to find: putty\sshdh.c
WARNING: Failure to find: putty\sshdss.c
WARNING: Failure to find: putty\sshmd5.c
WARNING: Failure to find: putty\sshpubk.c
WARNING: Failure to find: putty\sshrand.c
WARNING: Failure to find: putty\sshrsa.c
WARNING: Failure to find: putty\sshsh256.c
WARNING: Failure to find: putty\sshsh512.c
WARNING: Failure to find: putty\sshsha.c
WARNING: Failure to find: putty\sshshare.c
WARNING: Failure to find: putty\sshzlib.c
WARNING: Failure to find: putty\telnet.c
WARNING: Failure to find: putty\terminal.c
WARNING: Failure to find: putty\timing.c
WARNING: Failure to find: putty\tree234.c
WARNING: Failure to find: putty\version.c
WARNING: Failure to find: putty\wcwidth.c
WARNING: Failure to find: putty\wildcard.c
WARNING: Failure to find: putty\x11fwd.c
WARNING: Failure to find: putty\import.c
WARNING: Failure to find: putty\charset\fromucs.c
WARNING: Failure to find: putty\charset\macenc.c
WARNING: Failure to find: putty\charset\localenc.c
WARNING: Failure to find: putty\charset\mimeenc.c
WARNING: Failure to find: putty\charset\sbcs.c
WARNING: Failure to find: putty\charset\toucs.c
WARNING: Failure to find: putty\charset\slookup.c
WARNING: Failure to find: putty\charset\utf8.c
WARNING: Failure to find: putty\charset\xenc.c
WARNING: Failure to find: putty\windows\winmisc.c
WARNING: Failure to find: putty\windows\windefs.c
WARNING: Failure to find: putty\windows\wintime.c
WARNING: Failure to find: putty\windows\wincfg.c
WARNING: Failure to find: putty\windows\winnet.c
WARNING: Failure to find: putty\windows\winnoise.c
WARNING: Failure to find: putty\windows\winprint.c
WARNING: Failure to find: putty\windows\winproxy.c
WARNING: Failure to find: putty\windows\winser.c
WARNING: Failure to find: putty\windows\winstore.c
WARNING: Failure to find: putty\windows\winucs.c
WARNING: Failure to find: putty\windows\winhandl.c
WARNING: Failure to find: putty\windows\winhelp.c
WARNING: Failure to find: putty\windows\winpgntc.c
WARNING: Failure to find: putty\windows\winshare.c
WARNING: Failure to find: putty\windows\winutils.c
WARNING: Failure to find: putty\windows\winx11.c
WARNING: Failure to find: putty\windows\winjump.c
WARNING: Failure to find: putty\windows\wingss.c
WARNING: Failure to find: putty\sshgssc.c
WARNING: Failure to find: putty\pgssapi.c

E:\QTlib\qputty-qt5>

**Comment by dsmorozov** [comment]
As it is stated in README.md Windows porting is not completed and won't build. Moreover you have some problems with git.
